version: '3'

services:
  elasticsearch:
    image: 'elasticsearch-marvel'
    networks:
      - wae
    build:
      context: .
      dockerfile: Dockerfile-elasticsearch
    ports:
      - '9300'
      - '9200'
  spring_app:
    image: 'spring-app'
    networks:
      - voc_mail
      - wae
      - voc_network
    depends_on:
      - elasticsearch
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - '${public_port:-80}'
    environment:
     - PUBLIC_ACCESS=${public_access:-http://whatstat.remip.eu} #e-mail related, see code
     - VIRTUAL_HOST=${virtual_host:-whatstat.remip.eu} #for voc nginx-proxy
     - mail.password=${mail.password}

networks:
  voc_mail:
    external: true
  voc_network:
    external: true
  wae:
