version: '3'

services:
  elasticsearch:
    image: 'elasticsearch-marvel'
    networks:
      - wae
    build:
      context: .
      dockerfile: Dockerfile-elasticsearch
    ports:
      - '9300'
      - '9200'
  spring_app:
    image: 'spring-app'
    networks:
      - voc_mail
      - wae
    depends_on:
      - elasticsearch
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - '8080:80'
      - '5005:5005'
    environment:
     - PUBLIC_ACCESS=http://vps1.remip.eu:8080/static/index-mail.html

networks:
  voc_mail:
    external: true
  wae:
