version: '3'

services:
  elasticsearch:
    image: 'elasticsearch-marvel'
    networks:
      - wae
    build:
      context: .
      dockerfile: Dockerfile-elasticsearch
    ports:
      - '9300'
      - '9200'
  spring_app:
    image: 'spring-app'
    networks:
#      - voc_mail
      - wae
#      - voc_network
    depends_on:
      - elasticsearch
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - '3000:80'
      - '5005:5005'
    environment:
     - PUBLIC_ACCESS=http://whatstat.remip.eu
     - VIRTUAL_HOST=whatstat.remip.eu #for nginx-proxy
     - mail.password=none
    volumes:
     - '~/.gradle/:/root/.gradle'
     - './app/:/project/'

networks:
#  voc_mail:
#    external: true
#  voc_network:
#    external: true
  wae:
